#!/usr/bin/python

import os
import shutil
import glob
import fnmatch
import json
import sys
import hashlib
import termios
import argparse

#--------------------------------------------------------------------------------
# Write a line of text to the console and log file

def logWrite(text):
   print text,
   log.write(text)

#--------------------------------------------------------------------------------
# Write a line of text to the console and log file

def logWriteLn(text):
   logWrite(text+"\n")

#--------------------------------------------------------------------------------
# Report an error to the console and log file

def logError(text):
   logWriteLn("ERROR: "+text)

#--------------------------------------------------------------------------------
# Calculate the MD5 checksum for a file

def md5(filename):

    hash = hashlib.md5()

    with open(filename) as file:
        for block in iter(lambda: file.read(4096), b""):
            hash.update(block)

    return hash.hexdigest()

#--------------------------------------------------------------------------------
# 

def restoreTermIO():
   tio = termios.tcgetattr(0)
   tio[3] = tio[3] | termios.ECHO | termios.ICANON
   termios.tcsetattr(0, termios.TCSANOW, tio)

#--------------------------------------------------------------------------------

def listGames(list):
   i=0
   for game in games_list:
      i=i+1
      print "#%02u  " % (i) + os.path.basename("Games/"+game)

#--------------------------------------------------------------------------------

def packGames(list):
   archive=os.getcwd()+"/Games.tar"
   if os.path.isfile(archive):
      os.remove(archive)
   os.system("tar cvf "+archive)

   for game in games_list:
      os.system("tar rvf "+archive+" Games/"+game)

   os.system("gzip "+archive)

#--------------------------------------------------------------------------------

def dump(path):
   filename=os.path.basename(path)
   os.system("Zif/zdmp "+path+" --out "+filename+".dmp")

#--------------------------------------------------------------------------------

def playOnZif(path):
   os.system(zif+" --term "+path)

#--------------------------------------------------------------------------------

def playOnFrotz(path):
   os.system(frotz+" "+path)

#--------------------------------------------------------------------------------

def testGame(engine, path, index, other_args):
   global errors, warnings

   status = -1
   logWriteLn("================================================================================")
   logWriteLn("Index : "+str(index))
   logWriteLn("File  : "+os.path.basename(path))
   logWriteLn("Path  : "+os.path.dirname(path))

   if not os.path.isfile(path):
      logError("Story file '"+path+"' not found")
   else:
      logWriteLn("MD5   : "+md5(path))
      logWriteLn("--------------------------------------------------------------------------------")

      input_file="input/"+os.path.basename(path)+".in"
      if not os.path.isfile(input_file):
         input_file="input/default.in"

      if engine == "zif":
         status = os.system(zif+" --batch --info --term --width 80 --print --input "+input_file+
                            " "+path+" "+other_args)

      elif engine == "frotz":
         status = os.system(frotz+" -p "+path+" < "+input_file+" | tee print.log")

      if status!=0:
         logError("Exited test #%u with a fault [%u]" % (index, status))

      out_log="print.log"
      if not os.path.isfile(out_log):
         logError("No output log '"+out_log+"'")
         errors = errors + 1
      else:
         with open(out_log) as f:
            for line in f:
               if "ERR:" in line:
                  errors = errors + 1
               if "WRN:" in line:
                  warnings = warnings + 1
               logWrite(line)
         os.remove(out_log)

   return status 

#--------------------------------------------------------------------------------

def testAllGames(engine):
   index=0
   clean=0
   for game in games_list:
      index=index+1
      if testGame(engine, "Games/"+game, index, "") == 0:
         clean=clean+1
      

   logWriteLn("")
   logWriteLn("================================================================================")
   logWriteLn("Games      : %8u" % (len(games_list)))
   logWriteLn("Clean exit : %8u" % (clean))
   logWriteLn("Errors     : %8u" % (errors))
   logWriteLn("Warnings   : %8u" % (warnings))
   logWriteLn("--------------------------------------------------------------------------------")

#--------------------------------------------------------------------------------

def getGames(cache_dir, story_list_file):

   path_list = ["/if-archive/infocom/interpreters/tools/",
                "/if-archive/infocom/demos/",
                "/if-archive/phoenix/hints/zcode/",
                "/if-archive/scott-adams/games/zcode/",
                "/if-archive/games/zcode/"]

   for path in path_list:
      os.system("Zif/zcrape --path "+path+" --cache "+cache_dir)

   # Create list of interesting file extensions
   ext_list = []
   for version in range(8):
      ext_list += ['z'+str(version+1)]
      ext_list += ['Z'+str(version+1)]
   ext_list += ['zblorb']

   # Find and decompress zip files
   for filename in glob.glob(cache_dir+'/*.zip'):
      extract_dir=filename+"_extract"

      if not os.path.isdir(extract_dir):
         os.system("mkdir "+extract_dir)
         os.system("unzip -d "+extract_dir+" "+filename)

      for ext in ext_list:
         for root, dirnames, filenames in os.walk(extract_dir):
            for filename in fnmatch.filter(filenames, '*.'+ext):
               nice_filename=filename.replace(' ', '_')
               nice_filename=nice_filename.replace("'", '_')
               nice_filename=nice_filename.replace('(', '_')
               nice_filename=nice_filename.replace(')', '_')
               shutil.copy2(root+'/'+filename, cache_dir+'/'+nice_filename)

   # Compile a list of all the files
   game_list = []

   game_list += ["Games/Extra/crashme.z5"]
   game_list += ["Games/Extra/etude.z5"]
   game_list += ["Games/Extra/gntests.z5"]
   game_list += ["Games/Extra/random.z5"]

   for ext in ext_list:
      for filename in glob.glob(cache_dir+'/*.'+ext):
         game_list += [filename]

   game_list.sort()

   with open(story_list_file, 'w') as outfile:
      for game in game_list:
         game=game.replace("Games/", "")
         outfile.write(game+'\n')

   return

#--------------------------------------------------------------------------------

parser=argparse.ArgumentParser(description='Test Zif')

parser.add_argument('-a', '--all', dest='all', action='store_true',
                    help="Pull source, build Zif for debug, get story files and run all tests")

parser.add_argument('-f', '--frotz', dest='frotz', action='store_true',
                    help="Use Frotz not Zif")

parser.add_argument('-b', '--build-dbg', dest='build_dbg', action='store_true',
                    help="Pull latest source and rebuild debug Zif")
parser.add_argument('-B', '--build-rel', dest='build_rel', action='store_true',
                    help="Pull latest source and rebuild release Zif")

parser.add_argument('-g', '--get', dest='get', action='store_true',
                    help="Get story files")

parser.add_argument('-l', '--list', dest='list', action='store_true',
                    help="list tests without running them")
parser.add_argument('-p', '--pack', dest='pack', action='store_true',
                    help="create a package of story files")

parser.add_argument('-r', '--run', dest='run', action='store_true',
                    help="run all the tests")

parser.add_argument('-d', '--dump', dest='dump', metavar='#', type=int, default=0,
                    help="Dump the story file")
parser.add_argument('-t', '--test', dest='test_one', metavar='#', type=int, default=0,
                    help="Run a single test on Zif")
parser.add_argument('-z', '--zif', dest='play', metavar='#', type=int, default=0,
                    help="Play story")
parser.add_argument('-w', '--write', dest='write', metavar='#', type=int, default=0,
                    help="Write test input")

args=parser.parse_args()

#--------------------------------------------------------------------------------

if args.all:
   args.build_dbg = True
   args.get       = True
   args.run       = True

if args.test_one:
   args.dump = args.test_one

#--------------------------------------------------------------------------------

frotz             = os.environ['HOME']+"/OpenSource/frotz-2.43d/frotz"
frotz             = "frotz"
zif               = "Zif/zif"
cache_dir         = "Games/Downloads"
story_list_file   = "Games/list"
test_all_out_file = "all.out"

#--------------------------------------------------------------------------------

log=0
errors=0
warnings=0

if args.build_dbg or args.build_rel:
   os.chdir("Zif")
   os.system("git pull --rebase --recurse")
   if args.build_rel:
      os.system("scons debug=0")
   else:
      os.system("scons debug=1")
   os.chdir("..")

if args.get:
   getGames(cache_dir, story_list_file)

games_list=[]
with open(story_list_file, "r") as infile:
   games_list = infile.readlines()
games_list=[line.strip() for line in games_list]

if args.run:
   with open(test_all_out_file, "w") as log:
      if args.frotz:
         testAllGames("frotz")
      else:
         testAllGames("zif")
   os.system("git diff "+test_all_out_file)

if args.list:
   listGames(games_list)

if args.pack:
   packGames(games_list)

if args.play!= 0:
   path=games_list[args.play - 1]
   if args.frotz:
      playOnFrotz(path)
   else:
      playOnZif(path)

if args.dump != 0:
   dump("Games/"+games_list[args.dump - 1])

if args.test_one != 0:
   path="Games/"+games_list[args.test_one - 1]
   filename=os.path.basename(path)
   with open(filename+".out", "w") as log:
      if args.frotz:
         testGame("frotz", path, args.test_one, "")
      else:
         testGame("zif", path, args.test_one, "--trace")
         os.rename("trace.log", filename+".trc")

if args.write != 0:
   path="Games/"+games_list[args.write - 1]
   filename=os.path.basename(path)
   os.system(zif+" -k --term "+path)
   os.rename("key.log", "input/"+filename+".in")

restoreTermIO()
